catalog_name: mlops_students
schema_name: tanialemosribeiro

# preprocessing and model training
num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - required_car_parking_space
  - lead_time
  - arrival_year
  - arrival_month
  - arrival_date
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type

target: booking_status

test_size: 0.2

# model training
experiment_name: "/Shared/hotel-cancels"

# model serving
lookup_features:
  - "no_of_adults"
  - "no_of_children"
  - "repeated_guest"
  - "no_of_previous_cancellations"

prediction: predicted_cancel

serving_endpoint_name: "hotel-cancels-feature-serving"

feature_table_name: "hotel_cancels_preds"
online_table_name: "hotel_cancels_preds_online"
